### ISSUE TITLE
Not compiling, Error on SoftwareSerial

### ISSUE THREAD

**Issue by domhit** [empty88/OptoLink#1]
Hi, tried to compile your code, changed the wifi and mqtt settings accordingly. When I try build I get following error:

`src\viessmann.cpp: In function 'void setupVito()':
src\viessmann.cpp:63:20: error: cannot convert 'SoftwareSerial*' to 'HardwareSerial*'
Compiling .pio\build\d1_mini\lib5e3\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
   63 |     VitoWiFi.setup(&swSer);
      |                    ^~~~~~
      |                    |
      |                    SoftwareSerial*
In file included from .pio\libdeps\d1_mini\VitoWiFi\src/VitoWiFi.hpp:77,
                 from .pio\libdeps\d1_mini\VitoWiFi\src/VitoWiFi.h:30,
                 from include/viessmann.h:4,
                 from src\viessmann.cpp:1:
.pio\libdeps\d1_mini\VitoWiFi\src/VitoWiFi.cpp:48:46: note:   initializing argument 1 of 'void VitoWiFiClass< <template-parameter-1-1> >::setup(HardwareSerial*) [with P = OptolinkP300]'
   48 | void VitoWiFiClass<P>::setup(HardwareSerial* serial) {
      |                              ~~~~~~~~~~~~~~~~^~~~~~`

Could you help me, I have no idea what that means. Thanks alot

**Comment by empty88** [comment]
Hi,
VitoWifi was made to use with HardwareSerial only. I wanted to use SoftwareSerial so I changed the VitoWiFi Lib (replaced HardwareSerial with SoftwareSerial). That is why using VitoWiFi's public available version produces this error.
I added the customized VitoWiFi library with my last commit.
Build should work now.

Regards
eMpTy

**Comment by empty88** [comment]
Hi @sprabtor,

I see some differences in version numbers.
I am using Espressif 8266 version 4.0.1 so my EspSoftwareSerial version is 6.12.7

I comitted a new platformio.ini to force 4.0.1. I think that should do it for you.

Let me hear if it works.

Best regards
eMpTy

**Comment by sprabtor** [comment]
Thanks that solved the issue
