### ISSUE TITLE
Zeitangabe bestimmen in stoerungsmeldungCallbackHandler

### ISSUE THREAD

**Issue by gitzila** [empty88/OptoLink#2]
Hi,

habe mich von Deinem Sourcecode für mein Projekt inspirieren lassen (vielen lieben Dank für das Teilen). Kann es sein, dass in der Methode "stoerungsmeldungCallbackHandler" die Uhrzeit nicht richtig bestimmt wird? Bei meiner Vitodens kommt die Zeit anscheinend in der Form MM:HH:SS in den Fehlermeldungen. Hatte gestern Abend mal einen Fehler provoziert und in der Meldung stand dann "02:22:47", und es war nicht 2:00 Uhr :-) - eher 22:00.

Vielleicht ist auch die interne Uhr der Heizung defekt, aber die Zeitprogramme laufen eigentlich recht genau (+- 2 Minuten).

LG

Frank

**Comment by empty88** [comment]
Hi Frank,
ob das so passt, weiß ich ehrlich gesagt nicht, da ich es nie richtig getestet habe. In der Tat habe ich mich bei mir auch gefragt, ob das denn wirklich richtig ist. Rein logisch sollte es richtig sein, aber wer weiß, was Viessmann da gemacht hat.

Hast du einen Tipp für mich wie ich relativ leicht einen Fehler provoziere? Dann teste ich das bei mir und gebe Rückmeldung.

Viele Grüße
eMpTy

**Comment by gitzila** [comment]
Moin,

habe mich nochmal mit den Rohdaten aus dem Fehlerprotokoll auseinander gesetzt, denn die Zeiten passten immer noch nicht so richtig. Ich lese mit Deinem Code die Fehlerzeile ein:


char dpBuffer[128];
value.getString(dpBuffer,128);
String dpString = String(dpBuffer);

In meinem letzten Fehlereintrag habe ich diese Rohdaten:

**f42022123005110952**

Indexe (0-basiert): 

0-1 Fehlercode: F4 = 244 (=Flammensignal nicht...)
2-5 Jahr mit 4 Stellen = 2022
6-7 Monat mit 2 Stellen = 12
8-9 Tag mit 2 Stellen = 31
10-11 Unbekannt, diese 2 Stellen sind in meinen 10 Fehlereinträgen im Protokoll 01 bis 05, keine Ahnung was das bedeutet
12-13 Stunde mit 2 Stellen = 11
14-15 Minute mit 2 Stellen = 09
16-17 Sekunde mit 2 Stellen = 52

Die Zeit passt auf etwa 1 Minute genau.

Ich lese den String dann ins ISO-Format "JJJJ-MM-TT HH:mm:SS", lässt sich schön sortieren:

String timeString = dpString.substring(2,6) + "-" + dpString.substring(6,8) + "-" + dpString.substring(8,10) + " " + dpString.substring(12,14) + ":" + dpString.substring(14,16) + ":" + dpString.substring(16,18);
      
Meine letzten 10 Protokolleinträge:

f42022123005110952 [244] Flammensignal nicht vorhanden
f42022123005110536 [244] Flammensignal nicht vorhanden
f42022122904224728 [244] Flammensignal nicht vorhanden
a82022122002104832 [168] Unbekannter Fehler
c72022112902130256 [199] Falsche Codierung der Heizkreispumpe
a82022111004133456 [168] Unbekannter Fehler
a82022101102142608 [168] Unbekannter Fehler
a82022052301110328 [168] Unbekannter Fehler
c72022041404162952 [199] Falsche Codierung der Heizkreispumpe
c72022041404162536 [199] Falsche Codierung der Heizkreispumpe

Diese ominöse Zahl zwischen Datum und Uhrzeit ist dann wohl auch keine Art Zähler oder Angabe zur Schwere des Fehlers. Ich kann da kein Muster erkennen. Vielleicht hast Du 'ne Idee?

Fehler provozieren ist einfach:
Gashahn zu und Schorsteinfegermodus anschalten. Dann orgelt der Brenner ne Weile rum und geht nach 1-2 Minuten auf Störung. Ist die harte Tour, klappt aber immer :-)

Guten Rutsch!

**Comment by empty88** [comment]
Hi Frank,

ok, das brauche ich nicht zu provozieren, das scheint ziemlich eindeutig.
Ich werde, das Überspringen der Stellen 10 und 11 nachher bei mir testen. In meinen bisherigen "Regelbetrieb"-Meldungen habe ich die "05" als Stunde, was nicht sein kann, weil die Wartung der Heizung definitiv nicht um 5 Uhr gemacht wurde.
Das war mir bisher nicht so ganz klar :-D
Diese "05" passt zu deinen Erkenntnissen. 

Vielen Dank für deine Mühe!

Ich melde mich wieder
eMpTy

**Comment by empty88** [comment]
Hi Frank,
die Stellen 10-11 sind anscheinend der Wochentag. Habe deine Rohdaten im Kalender abgeglichen.
01 Montag bis 05 Freitag, 06 und 07 werden vermutlich dann Samstag und Sonntag sein.

Viele Grüße
eMpTy

**Comment by gitzila** [comment]
Hi, super, das mit dem WT wäre mir nie aufgefallen, oh Mann :-)

Aber sag mal: Hast Du bei den Adressen für Störung oder Brennerstörung jemals andere Werte als 0 bekommen? Ich bekomme aus der Schnittstelle immer nur "0". Habe das nun so gelöst, dass ich mir aus dem Fehlerprotokoll den letzten Eintrag merke (un im Flash sichere) und dann alle 30 Sekunden mit der aktuellen Liste aus dem Vito abgleiche. Gibt es dort einen neueren Eintrag, dann setze ich mir ein eigenes Fehlerflag und schicke mir per Telegram Bot eine Nachricht auf's Handy. Funktioniert super.

Und eine andere Sache noch: Taktet Deine Heizung auch so furchtbar oft? Wenn es nicht gerade -10 Grad hat, dann springt die Heizung alle 2 Minuten für 20 Sekunden an und schaltet dann ab, weil der Kessel zu warm wird. Ich habe das so gelöst und überhaupt erst deswegen das Gebastel mit dem ESP und dem Optolink angefangen, dass ich alle 2 Sekunden den Brennerstatus abfrage, bei Start dann die Raum-Soll RT auf 37 Grad hochsetze und nach 1 Minute wieder auf Normalwert zurück. In der einen Minute kommt dann genug kühles Wasser aus dem Haus nach und der Brenner läuft dann schön 10-20 Minuten durch. Grob gepeilt schont das nicht nur die ganze Anlage (statt 30 Starts in der Stunde nun 25 am Tag) sondern spart auch Gas. Bei den eisigen -15 Grad neulich waren wir hier bei unter 7 m³ am Tag.

Falls Du ein ähnliches Problem mit Deiner Heizung hast, können wir uns gern austauschen.

LG
Frank
