### ISSUE TITLE
Abfrage der Device-ID für alternative Adressen

### ISSUE THREAD

**Issue by fitim7** [empty88/OptoLink#4]
Hi, 

laut [https://github.com/openv/openv/wiki/Geräte](url) folgt die Info:

> Jede Steuerungsfamilie hat eine zwei Byte lange Device-Id. Diese Device-Id kann bei vielen Steuerungen über die Adresse 0xf8 abgefragt werden.

[Hier](https://github.com/bertmelis/VitoWiFi/issues/37#issuecomment-386428845) sagt @bertmelis, dass die Id über DPRaw ermittelt werden kann.

Wenn ich ganz stumpf die Viessmann.cpp ergänze um folgenden Code:
`DPRaw deviceid("deviceid", "", 0x00f8);`
dann erhalte ich kein Ergebnis.

Wie kann ich das lösen?

Danke im Vorfeld :)

**Comment by empty88** [comment]
Hi fitim7,
hab es gerade bei mir probiert und im VitoWiFi-Wiki nachgelesen. Bei der Verwendung von DPRaw musst du mit setLength() die zu lesenden Bytes festlegen, 2 oder 4 (erweiterte DeviceId). Kannst du dir bei den Störungsmeldungs-Datenpunkten abgucken in `void setupVito()`. Hatte es auch nicht mehr auf dem Schirm.

Viele Grüße
eMpTy

**Comment by fitim7** [comment]
Top! Das hat direkt geklappt. Manchmal sieht man den Wald vor lauter Bäumen nicht mehr... :)
