### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by tunip** [empty88/OptoLink#5]
Vielen Dank für dieses Projekt. Ich bekomme leider nur einen error=1 in MQTT zurück. Welche Möglichkeiten habe ich zum Debugging, z.B. ob der selbstgebaute Lesekopf korrekt funktioniert?

**Comment by fitim7** [comment]
> Vielen Dank für dieses Projekt. Ich bekomme leider nur einen error=1 in MQTT zurück. Welche Möglichkeiten habe ich zum Debugging, z.B. ob der selbstgebaute Lesekopf korrekt funktioniert?

Also die beste Möglichkeit zum debuggen eines Lesekopfs ist es mit der handykamera darauf zu schauen, ob sie Sendediode leuchtet.

**Comment by empty88** [comment]
Überprüf auch mal, ob du nicht Lese- (Transistor) und Schreibrichtung (LED) an der Heizung vertauscht hast. Ist mir am Anfang auch mal passiert. Ich hab lange gebraucht um das zu bemerken...

**Comment by tunip** [comment]
Danke für die schnelle Antwort. Die lila IR LED scheint nichts zu senden. Die Handykamera zeigt keine Reaktion.
Habe zusätzlich zu der SFH-487-2 noch die SIR 204 EVL bestellt und baue den Lesekopf dann neu auf. Ich gebe Feedback nächste Woche.
