### ISSUE TITLE
Blog leider down

### ISSUE THREAD

**Issue by jaegerschnitzel** [empty88/OptoLink#7]
Wollte mir weitere Details auf deinem Blog anschauen, aber leider ist dieser derzeit down.
https://blog.mt88.eu/2022/10/27/viessmann-heizungsdaten-2-0/

Es gab einen kritischen Fehler auf deiner Website.

**Comment by empty88** [comment]
Danke für den Hinweis!
Ein WordPress-Plugin war es Schuld. Seite ist wieder erreichbar.
